const DEFAULT_BASE_URL = 'https://file.pizza'

const EXIT_CODES = {
  OK: 0,
  USAGE: 2,
  NETWORK: 3,
  PASSWORD: 4,
  DOWNLOAD: 5,
}

const ERROR_CODES = {
  USAGE: 'E_USAGE',
  BROWSER_UNAVAILABLE: 'E_BROWSER_UNAVAILABLE',
  CONNECT_TIMEOUT: 'E_CONNECT_TIMEOUT',
  UPLOAD_OFFLINE: 'E_UPLOAD_OFFLINE',
  PASSWORD_INVALID: 'E_PASSWORD_INVALID',
  PASSWORD_REQUIRED: 'E_PASSWORD_REQUIRED',
  DOWNLOAD_FAILED: 'E_DOWNLOAD_FAILED',
}

const TIMEOUTS = {
  pageLoadMs: 30_000,
  stateReadyMs: 90_000,
  shareLinkReadyMs: 45_000,
  downloadStartMs: 60_000,
}

module.exports = {
  DEFAULT_BASE_URL,
  EXIT_CODES,
  ERROR_CODES,
  TIMEOUTS,
}
